"""update Log model

Revision ID: 0cf7e4f7e00a
Revises: 8c1acc2b153b
Create Date: 2025-08-12 15:23:18.578791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cf7e4f7e00a'
down_revision: Union[str, Sequence[str], None] = '8c1acc2b153b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'logs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'logs', type_='foreignkey')
    op.drop_column('logs', 'user_id')
    # ### end Alembic commands ###
