"""remove 'position_size' field from Instrument model

Revision ID: 12e4948250f5
Revises: 7643b7a018d9
Create Date: 2025-08-24 15:53:25.659231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12e4948250f5'
down_revision: Union[str, Sequence[str], None] = '7643b7a018d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instruments', 'position_size')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instruments', sa.Column('position_size', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
