"""add 'deal_id' field to Order model

Revision ID: 2d62d25a9fb1
Revises: 4e581d65baee
Create Date: 2025-08-31 15:06:33.300409

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2d62d25a9fb1"
down_revision: Union[str, Sequence[str], None] = "4e581d65baee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("deal_id", sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "deal_id")
    # ### end Alembic commands ###
