"""remove maximum_trades_per_instrument_per_day field from UserSettings model

Revision ID: 31625bb15b0e
Revises: 12e4948250f5
Create Date: 2025-08-24 15:58:43.299292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31625bb15b0e'
down_revision: Union[str, Sequence[str], None] = '12e4948250f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'maximum_trades_per_instrument_per_day')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('maximum_trades_per_instrument_per_day', sa.INTEGER(), autoincrement=False, nullable=False, comment='Maximum trades per instrument per day'))
    # ### end Alembic commands ###
