"""add user_id field to Order model

Revision ID: 3704f3e74d7e
Revises: 88ced0384de6
Create Date: 2025-08-31 14:39:53.378188

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3704f3e74d7e"
down_revision: Union[str, Sequence[str], None] = "88ced0384de6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("user_id", sa.Uuid(), nullable=True))
    op.execute(
        """
        UPDATE orders
        SET user_id = instruments.user_id
        FROM instruments
        WHERE orders.instrument_id = instruments.id
    """
    )
    op.alter_column("orders", "user_id", nullable=False)
    op.create_foreign_key(
        None, "orders", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "orders", type_="foreignkey")
    op.drop_column("orders", "user_id")
    # ### end Alembic commands ###
