"""add 'identifier' field to Log model

Revision ID: 40cc3ebc7e7d
Revises: 257ebbc19800
Create Date: 2025-08-16 15:19:56.143889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40cc3ebc7e7d'
down_revision: Union[str, Sequence[str], None] = '257ebbc19800'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('identifier', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logs', 'identifier')
    # ### end Alembic commands ###
