"""add 'is_open' field to Order model

Revision ID: 4e581d65baee
Revises: 3704f3e74d7e
Create Date: 2025-08-31 14:45:33.791160

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4e581d65baee"
down_revision: Union[str, Sequence[str], None] = "3704f3e74d7e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("is_open", sa.Boolean(), nullable=True))
    op.execute(
        """
        UPDATE orders
        SET is_open = TRUE
        WHERE is_open IS NULL
    """
    )
    op.alter_column("orders", "is_open", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "is_open")
    # ### end Alembic commands ###
