"""remove unique constraint from Order.instrument field

Revision ID: 51d1616ceb42
Revises: 2d62d25a9fb1
Create Date: 2025-09-02 13:11:36.690038

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "51d1616ceb42"
down_revision: Union[str, Sequence[str], None] = "2d62d25a9fb1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("orders_instrument_id_key"), "orders", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("orders_instrument_id_key"),
        "orders",
        ["instrument_id"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
