"""add last_alert_received_at field to Instrument model

Revision ID: 54b653a0c812
Revises: 978ec253b3d2
Create Date: 2025-10-01 09:19:27.409763

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "54b653a0c812"
down_revision: Union[str, Sequence[str], None] = "978ec253b3d2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "instruments",
        sa.Column("last_alert_received_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("instruments", "last_alert_received_at")
    # ### end Alembic commands ###
