"""remove auto-updating last_login field from User model

Revision ID: 603f69c7fdf1
Revises: e56fc82e4f41
Create Date: 2025-08-26 19:08:41.720784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '603f69c7fdf1'
down_revision: Union[str, Sequence[str], None] = 'e56fc82e4f41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
