"""increate deal_reference field length in Order model

Revision ID: 7643b7a018d9
Revises: e8c34de45593
Create Date: 2025-08-23 21:35:43.902615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7643b7a018d9'
down_revision: Union[str, Sequence[str], None] = 'e8c34de45593'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'deal_reference',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.String(length=128),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'deal_reference',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=12),
               existing_nullable=False)
    # ### end Alembic commands ###
