"""modify instrument max position size to Decimal instead of int

Revision ID: 88ced0384de6
Revises: ef18b3f81a58
Create Date: 2025-08-31 12:18:32.783413

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "88ced0384de6"
down_revision: Union[str, Sequence[str], None] = "ef18b3f81a58"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "instruments",
        "max_position_size",
        existing_type=sa.INTEGER(),
        type_=sa.Numeric(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "instruments",
        "max_position_size",
        existing_type=sa.Numeric(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
