"""add trading_view_price_multiplier field to Instrument model

Revision ID: 978ec253b3d2
Revises: 51d1616ceb42
Create Date: 2025-09-07 10:06:17.383497

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "978ec253b3d2"
down_revision: Union[str, Sequence[str], None] = "51d1616ceb42"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "instruments",
        sa.Column("trading_view_price_multiplier", sa.Numeric(), nullable=True),
    )
    op.execute("UPDATE instruments SET trading_view_price_multiplier = 1.0")
    op.alter_column(
        "instruments",
        "trading_view_price_multiplier",
        nullable=False,
        server_default=sa.text("1.0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("instruments", "trading_view_price_multiplier")
    # ### end Alembic commands ###
