"""initial migration

Revision ID: df649c1b5a15
Revises: 
Create Date: 2025-08-04 21:24:09.201865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df649c1b5a15'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('UNSPECIFIED', 'AUTHENTICATION', 'ALERT', 'TRADE', 'ORDER', 'ERROR', name='logtype'), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('refresh_token')
    )
    op.create_table('instruments',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('market_and_symbol', sa.String(length=255), nullable=False),
    sa.Column('ig_epic', sa.String(length=255), nullable=False),
    sa.Column('yahoo_symbol', sa.String(length=255), nullable=False),
    sa.Column('atr_stop_loss_period', sa.Integer(), nullable=False),
    sa.Column('atr_stop_loss_multiple', sa.Numeric(), nullable=False),
    sa.Column('atr_profit_target_period', sa.Integer(), nullable=False),
    sa.Column('atr_profit_multiple', sa.Numeric(), nullable=False),
    sa.Column('position_size', sa.Integer(), nullable=False),
    sa.Column('max_position_size', sa.Integer(), nullable=True),
    sa.Column('opening_price_multiple', sa.Numeric(), nullable=False),
    sa.Column('next_dividend_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_settings',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('mode', sa.Enum('DEMO', 'LIVE', name='usersettingsmode'), nullable=False),
    sa.Column('demo_api_key', sa.Text(), nullable=True),
    sa.Column('demo_username', sa.Text(), nullable=True),
    sa.Column('demo_password', sa.Text(), nullable=True),
    sa.Column('demo_webhook_url', sa.Text(), nullable=True),
    sa.Column('live_api_key', sa.Text(), nullable=True),
    sa.Column('live_username', sa.Text(), nullable=True),
    sa.Column('live_password', sa.Text(), nullable=True),
    sa.Column('live_webhook_url', sa.Text(), nullable=True),
    sa.Column('maximum_order_age_in_minutes', sa.Integer(), nullable=False, comment='Maximum age of an order in minutes'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_settings')
    op.drop_table('instruments')
    op.drop_table('users')
    op.drop_table('logs')
    # ### end Alembic commands ###
