"""add spreadbet account id field to user settings model

Revision ID: f7c955738327
Revises: f5036ee13c64
Create Date: 2025-08-08 21:46:22.275132

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f7c955738327"
down_revision: Union[str, Sequence[str], None] = "f5036ee13c64"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_settings", sa.Column("demo_account_id", sa.Text(), nullable=True)
    )
    op.add_column(
        "user_settings", sa.Column("live_account_id", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_settings", "live_account_id")
    op.drop_column("user_settings", "demo_account_id")
    # ### end Alembic commands ###
